# Generated by Django 3.2 on 2021-04-21 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_home_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='github_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
